### ISSUE TITLE
Cache failed derivations

### ISSUE THREAD

**Issue by Mic92** [nix-community/buildbot-nix#77] opened 2024-01-05 07:53 UTC
We currently do one retry, which is fine.
However if a future push shows that the derivation failed in the past, we should cache the failure.
If possible we should add a retry button to retry the derivation anyway.

**Comment by zowoq** [comment] 2024-09-20 06:18
Looks like https://github.com/nix-community/buildbot-nix/issues/224 was dupe of this issue?

**Comment by MagicRB** [comment] 2024-09-22 23:17
Indeed.

**Closed by MagicRB** 2024-09-22 23:17 UTC
Labels: enhancement
